import uuid

from fastapi import APIRouter, Depends, UploadFile, File, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.crop import Crop, CropGrade, DiagnosisRecord
from app.models.user import User, UserRole
from app.schemas.crop import GradingResult, DiagnosisResult
from app.services.ai_service import (
    grade_crop_image,
    diagnose_plant_disease,
    get_disease_insight,
    get_grading_insight,
    get_sensor_insight,
)
from app.services.auth_service import get_current_user, require_role

router = APIRouter(prefix="/ai", tags=["ai"])

FarmerUser = Depends(require_role(UserRole.FARMER, UserRole.ADMIN))


@router.post("/grade/{crop_id}", response_model=GradingResult)
async def grade_crop(
    crop_id: uuid.UUID,
    file: UploadFile = File(...),
    current_user: User = FarmerUser,
    db: AsyncSession = Depends(get_db),
):
    crop = await db.get(Crop, crop_id)
    if not crop or crop.farmer_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Crop not found")

    image_bytes = await file.read()
    try:
        result = await grade_crop_image(image_bytes, file.filename or "image.jpg", str(crop_id))
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Layanan AI tidak tersedia saat ini. Coba beberapa saat lagi.",
        )

    crop.grade = CropGrade(result.grade)
    crop.grade_confidence = result.confidence
    await db.commit()
    return result


@router.post("/diagnose", response_model=DiagnosisResult)
async def diagnose(
    file: UploadFile = File(...),
    current_user: User = FarmerUser,
    db: AsyncSession = Depends(get_db),
):
    image_bytes = await file.read()
    try:
        result = await diagnose_plant_disease(image_bytes, file.filename or "image.jpg")
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Layanan AI tidak tersedia saat ini. Coba beberapa saat lagi.",
        )

    record = DiagnosisRecord(
        farmer_id=current_user.id,
        image_url="",
        disease_name=result.disease_name,
        confidence=result.confidence,
        recommendation=result.recommendation,
    )
    db.add(record)
    await db.commit()
    return result



# ─── LLM Insight Endpoints ────────────────────────────────────────────────────


class DiseaseInsightRequest(BaseModel):
    """Request body for disease insight."""
    disease_name: str
    confidence: float
    is_healthy: bool = False
    sensor_data: dict | None = None


class GradingInsightRequest(BaseModel):
    """Request body for grading insight."""
    grade: str
    confidence: float
    grade_a_prob: float = 0.0
    grade_b_prob: float = 0.0
    grade_c_prob: float = 0.0
    sensor_data: dict | None = None


class SensorInsightRequest(BaseModel):
    """Request body for sensor insight."""
    temperature: float | None = None
    humidity: float | None = None
    soil_moisture: float | None = None
    ph: float | None = None


class InsightResponse(BaseModel):
    """Response containing LLM-generated insight."""
    insight: str


@router.post("/insight/disease", response_model=InsightResponse)
async def disease_insight_endpoint(
    data: DiseaseInsightRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Get LLM-generated treatment recommendation for a detected disease.

    Combines disease detection result with contextual farming advice
    generated by Google Gemini in Indonesian.
    """
    insight = await get_disease_insight(
        disease_name=data.disease_name,
        confidence=data.confidence,
        is_healthy=data.is_healthy,
        sensor_data=data.sensor_data,
    )
    if not insight:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Layanan insight tidak tersedia saat ini.",
        )
    return InsightResponse(insight=insight)


@router.post("/insight/grading", response_model=InsightResponse)
async def grading_insight_endpoint(
    data: GradingInsightRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Get LLM-generated quality insight for a grading result.

    Provides market value context and tips to improve crop quality.
    """
    grade_probs = {
        "grade_a_prob": data.grade_a_prob,
        "grade_b_prob": data.grade_b_prob,
        "grade_c_prob": data.grade_c_prob,
    }
    insight = await get_grading_insight(
        grade=data.grade,
        confidence=data.confidence,
        grade_probs=grade_probs,
        sensor_data=data.sensor_data,
    )
    if not insight:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Layanan insight tidak tersedia saat ini.",
        )
    return InsightResponse(insight=insight)


@router.post("/insight/sensor", response_model=InsightResponse)
async def sensor_insight_endpoint(
    data: SensorInsightRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Get LLM-generated environmental analysis from sensor readings.

    Analyzes current field conditions and provides actionable farming advice
    generated by Google Gemini in Indonesian.
    """
    sensor_data = {
        "temperature": data.temperature,
        "humidity": data.humidity,
        "soil_moisture": data.soil_moisture,
        "ph": data.ph,
    }
    insight = await get_sensor_insight(sensor_data)
    if not insight:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Layanan insight tidak tersedia saat ini.",
        )
    return InsightResponse(insight=insight)
